/**
 * @file cluster.js
 * @description Utilities for building cluster donut Markers.
 *
 * Provides:
 * - A default 10-color palette for cluster slice coloring
 * - A color resolver supporting three input forms (object, array, undefined)
 * - An HTML element factory for donut cluster Markers
 *
 * The ShapeFactory SVG handles slice hover scaling natively.
 * This module only manages center-label text updates on slice hover.
 */

import { ShapeFactory } from '@kalisio/common-graphics'

// ── Default Palette ───────────────────────────────────────────────────────────

/**
 * Default 10-color palette used when no colors are specified in the layer definition.
 * Colors cycle if there are more than 10 classes.
 * @type {string[]}
 */
export const DEFAULT_CLUSTER_PALETTE = [
  '#e74c3c',
  '#3498db',
  '#2ecc71',
  '#f39c12',
  '#9b59b6',
  '#1abc9c',
  '#e67e22',
  '#34495e',
  '#e91e63',
  '#00bcd4'
]

// ── Color Resolver ────────────────────────────────────────────────────────────

/**
 * Normalizes the three accepted forms of `cluster.colors` into a plain object
 * mapping each class name to a hex color string.
 *
 * Accepted forms:
 * - `{ className: '#rrggbb', ... }` — explicit per-class mapping
 * - `['#rrggbb', '#rrggbb', ...]`   — list distributed by index (cyclic)
 * - `undefined`                      — fallback to DEFAULT_CLUSTER_PALETTE
 *
 * Any class not covered by the provided config falls back to the default palette.
 *
 * @param {string[]} classes - Ordered list of unique class values found in the data
 * @param {Object|string[]|undefined} colorConfig - Raw value from `cluster.colors`
 * @returns {{ [className: string]: string }}
 */
export function resolveClusterColors (classes, colorConfig) {
  if (!colorConfig) {
    // No config — assign palette colors by index
    return Object.fromEntries(
      classes.map((cls, i) => [cls, DEFAULT_CLUSTER_PALETTE[i % DEFAULT_CLUSTER_PALETTE.length]])
    )
  }

  if (Array.isArray(colorConfig)) {
    // List form — distribute by index, cycle if needed
    return Object.fromEntries(
      classes.map((cls, i) => [cls, colorConfig[i % colorConfig.length]])
    )
  }

  // Object form — use provided mapping, fall back to palette for missing classes
  return Object.fromEntries(
    classes.map((cls, i) => [
      cls,
      colorConfig[cls] ?? DEFAULT_CLUSTER_PALETTE[i % DEFAULT_CLUSTER_PALETTE.length]
    ])
  )
}

// ── Donut Marker Element ──────────────────────────────────────────────────────

/**
 * Builds an HTML element suitable for use as a MapLibre `Marker`.
 *
 * The element contains:
 * - An SVG chart (donut, pie, etc.) generated by `ShapeFactory`
 * - A centered `<span>` label that shows the total count by default,
 *   and the per-class count when hovering a slice
 *
 * @param {{ value: number, label: string, color: string }[]} slices
 *   Ordered slice descriptors.
 * @param {number} totalCount - Total number of features in the cluster
 * @param {string} shapeType - The shape to generate (e.g. 'donut', 'pie')
 * @returns {HTMLElement}
 */
export function buildClusterMarkerElement (slices, totalCount, shapeType = 'donut') {
  const factory = new ShapeFactory()

  // Filter out zero-value slices to keep parity with the generated SVG <path> elements
  const validSlices = slices.filter(s => s.value > 0)

  const shape = factory.build({
    shape: shapeType,
    radius: 40,
    color: validSlices.length === 1 ? validSlices[0].color : undefined,
    stroke: { color: '#ffffff', width: 2 },
    slices: validSlices
  })

  const svgString = shape.toSVG()

  // ── Wrapper (0x0) ────────────────────────────────────────────────────────────
  // Trick: the marker is wrapped in a 0x0 div.
  // MapLibre computes the offset relative to the element's size (which is 0).
  // This keeps the container perfectly centered via CSS, so it no longer "drifts" on zoom!
  const wrapper = document.createElement('div')
  wrapper.style.position = 'relative'
  wrapper.style.width = '0px'
  wrapper.style.height = '0px'

  // ── Container ────────────────────────────────────────────────────────────────
  const container = document.createElement('div')
  container.className = 'cluster-marker'
  container.style.position = 'absolute'
  // The container is offset by -40px to perfectly center it on the wrapper (0,0)
  container.style.top = '-40px'
  container.style.left = '-40px'
  container.style.display = 'inline-flex'
  container.style.justifyContent = 'center'
  container.style.alignItems = 'center'
  // ShapeFactory uses a radius of 40, hence 80x80
  container.style.width = '80px'
  container.style.height = '80px'
  container.innerHTML = svgString

  // The SVG element must fill the whole space and be absolutely
  // positioned so flexbox doesn't lay it out next to the span
  const svgEl = container.querySelector('svg')
  if (svgEl) {
    svgEl.style.position = 'absolute'
    svgEl.style.top = '0'
    svgEl.style.left = '0'
  }

  // ── Center label ─────────────────────────────────────────────────────────────
  const label = document.createElement('span')
  label.className = 'cluster-label'
  label.textContent = String(totalCount)

  // Styles to center the text and make it presentable
  label.style.position = 'relative'
  label.style.zIndex = '1'
  label.style.pointerEvents = 'none' // Crucial: keeps the text from blocking hover on the SVG slices underneath!
  label.style.fontWeight = 'bold'
  label.style.fontFamily = 'sans-serif'
  label.style.color = '#333'

  container.appendChild(label)

  // ── Slice hover — text update ─────────────────────────────────────────────────
  if (svgEl) {
    const paths = svgEl.querySelectorAll('path')
    paths.forEach((path, i) => {
      const slice = validSlices[i]
      if (!slice) return

      path.addEventListener('mouseenter', () => {
        label.textContent = String(slice.value)
      })
      path.addEventListener('mouseleave', () => {
        label.textContent = String(totalCount)
      })
    })
  }

  wrapper.appendChild(container)

  // The container is exposed so mouseenter/mouseleave listeners can be attached to it
  // (mouseenter doesn't bubble from a child up to a 0x0 parent)
  wrapper.hoverElement = container
  return wrapper
}
